version: '1'

services:

  app:

    build: .

    image: ${DOCKER_USER_ID}/jenkins

  production:

    image: ${DOCKER_USER_ID}/jenkins:${BUILD_NUMBER}

    command: python hello.py

    volumes:

      - .:/volume-jenkins

    ports:

      - "9090:8080"
