version: '2.0'

services:

  app:

    build: .

    image: ${DOCKER_USER_ID}/jenkins:v1.0

  production:

    image: ${DOCKER_USER_ID}/jenkins:v1.0:${BUILD_NUMBER}

    command: python hello.py

    volumes:

      - .:/volume-jenkins

    ports:

      - "9090:8080"
