apiVersion: v1
kind: Service
metadata:
  name: dev-kub
  labels:
    app.dev.server: service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 2222 # service의 port
    targetPort: 8080 # pod의 target port
  selector:
    app.dev.server: node # 연결 시킬 pod의 label
